# Generated by Django 2.0.4 on 2018-05-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.TimeField(choices=[('9:00', '09:00:00'), ('9:30', '09:30:00'), ('10:00', '10:00:00'), ('10:30', '10:30:00'), ('11:00', '11:00:00'), ('11:30', '11:30:00'), ('12:00', '12:00:00'), ('12:30', '12:30:00'), ('13:00', '13:00:00'), ('13:30', '13:30:00'), ('14:00', '14:00:00'), ('14:30', '14:30:00'), ('15:00', '15:00:00'), ('15:30', '15:30:00'), ('16:00', '16:00:00'), ('16:30', '16:30:00'), ('17:00', '17:00:00'), ('17:30', '17:30:00'), ('18:00', '18:00:00')]),
        ),
    ]
