# Generated by Django 2.0.4 on 2018-05-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_auto_20180506_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.TimeField(choices=[('09:00:00', '09:00'), ('09:30:00', '09:30'), ('10:00:00', '10:00'), ('10:30:00', '10:30'), ('11:00:00', '11:00'), ('11:30:00', '11:30'), ('12:00:00', '12:00')]),
        ),
    ]
