# Generated by Django 2.0.4 on 2018-05-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0004_auto_20180506_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KK', 'Kim Kardashian'), ('CJ', 'Caitlin Jenner'), ('KW', 'Kanye West')], max_length=2)),
                ('location', models.CharField(choices=[('CL', 'Central London'), ('NL', 'North London'), ('SL', 'South London'), ('EL', 'East London'), ('WL', 'West London')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointments.Barber')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
